baseurl = "/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
title = "Magical trees, take me home."
theme = "diary"
# googleAnalytics = "UA-123-45"

# paginate = 7

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

[params]
subtitle = "Magicwenli's blog"
favicon = "/img/favicon/favicon.ico"
enableGitalk = false
enableReadingTime=true
enableAutoDarkMode=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Magicwenli" # will set 'og:site_name'
description = "Markdown around"  # will set 'og:description'

[params.gitalk]
  owner = "magicwenli"
  repo = "magicwenli.github.io"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="magicwenli.github.io"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1
[[menu.main]]
url = "/about"
name = "关于我"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
[[menu.main]]
url = "/categories"
name = "分类"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 5

